-- Hayatımız Oyun Site v0.0.5
-- Bu sürümde Supabase zorunlu değildir.
-- Oyun kartları şu an demo veriyle çalışır.

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  series text,
  release_year text,
  status text default 'Planlandı',
  cover_url text,
  created_at timestamptz default now()
);
