-- Hayatımız Oyun Arşiv Sistemi v0.0.6
-- Bu sürümde Supabase zorunlu değildir.
-- SQL sadece hazırlık amaçlıdır, çalıştırmak şart değildir.

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  series text,
  release_year text,
  status text default 'Planlandı',
  genres text[] default '{}',
  tags text[] default '{}',
  cover_url text,
  created_at timestamptz default now()
);
